#!/bin/bash

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e paru -Syu;;
	2) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Right click to show upgradable packages" ;;
	3) notify-send "$(/usr/bin/pacman -Qu)" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

pacman -Qu | grep -Fcv "[ignored]" | sed "s/^/  /;s/$/ /;s/^  0 $//g"
